NoSuchMethodError: GroovyClassLoader.parseClass
As said in https://issues.jenkins-ci.org/browse/JENKINS-36434, the method parseClass(InputStream in) has been removed.
Use of the deprecated function : parseClass(InputStream in, String fileName).